### ISSUE TITLE
Overlapping of top right task bar

### ISSUE THREAD

**Issue by GithubUserLennard** [wirtzdan/logseq-paper-theme#5]
Hey guys,
While scrolling down the top right task bar and its icons are overlapping the text f.e. in the journal. without any blocker in between:
![image](https://user-images.githubusercontent.com/94683186/144720139-6096b145-0c86-4c69-b3cb-b30e8a8c80b3.png)
There is no color / blocker behind the icons so they are transparant in a way. While I do not know wherther this is intended or not, I find it a little bit irritating while scrolling down and prefer a intransparent background behind the icons just like in the default theme of logseq. 
Nonetheless your theme really looks great! Thank  you for providing it to the logseq community :)  
Greetings!

**Comment by wirtzdan** [comment]
I've just shipped an update to the Paper Theme. 

That should fix the issue!
