### ISSUE TITLE
the search icon isn't aligned

### ISSUE THREAD

**Issue by Ben9706** [wirtzdan/logseq-paper-theme#8]
I find the search icon isn't aligned.
My device:13-inch MacBook Pro, macOS Monterey
<img width="254" alt="截屏2022-02-15 下午7 07 44" src="https://user-images.githubusercontent.com/47425245/154050433-f362c8c9-774c-4e79-acfb-9cafbb292f05.png">

**Comment by huanhuan129** [comment]
I also find the problem, how can we fix that?

**Comment by wirtzdan** [comment]
I've just shipped an update to the Paper Theme, that fixes this issue. 

@Ben9706 @huanhuan129
